export type MatrixKey = { row: number; bit: number };

export const CAPS_SHIFT: MatrixKey = { row: 0, bit: 0 };
export const SYMBOL_SHIFT: MatrixKey = { row: 7, bit: 1 };

export const SPECTRUM_KEY_MATRIX: Record<string, MatrixKey> = {
  CAPS_SHIFT,
  SYMBOL_SHIFT,
  Z: { row: 0, bit: 1 },
  X: { row: 0, bit: 2 },
  C: { row: 0, bit: 3 },
  V: { row: 0, bit: 4 },
  A: { row: 1, bit: 0 },
  S: { row: 1, bit: 1 },
  D: { row: 1, bit: 2 },
  F: { row: 1, bit: 3 },
  G: { row: 1, bit: 4 },
  Q: { row: 2, bit: 0 },
  W: { row: 2, bit: 1 },
  E: { row: 2, bit: 2 },
  R: { row: 2, bit: 3 },
  T: { row: 2, bit: 4 },
  "1": { row: 3, bit: 0 },
  "2": { row: 3, bit: 1 },
  "3": { row: 3, bit: 2 },
  "4": { row: 3, bit: 3 },
  "5": { row: 3, bit: 4 },
  "0": { row: 4, bit: 0 },
  "9": { row: 4, bit: 1 },
  "8": { row: 4, bit: 2 },
  "7": { row: 4, bit: 3 },
  "6": { row: 4, bit: 4 },
  P: { row: 5, bit: 0 },
  O: { row: 5, bit: 1 },
  I: { row: 5, bit: 2 },
  U: { row: 5, bit: 3 },
  Y: { row: 5, bit: 4 },
  ENTER: { row: 6, bit: 0 },
  L: { row: 6, bit: 1 },
  K: { row: 6, bit: 2 },
  J: { row: 6, bit: 3 },
  H: { row: 6, bit: 4 },
  SPACE: { row: 7, bit: 0 },
  M: { row: 7, bit: 2 },
  N: { row: 7, bit: 3 },
  B: { row: 7, bit: 4 },
};

export const SYMBOL_SHIFT_CHARS: Record<string, MatrixKey> = {
  "!": { row: 3, bit: 0 },
  "@": { row: 3, bit: 1 },
  "#": { row: 3, bit: 2 },
  $: { row: 3, bit: 3 },
  "%": { row: 3, bit: 4 },
  "&": { row: 4, bit: 4 },
  "'": { row: 4, bit: 3 },
  "(": { row: 4, bit: 2 },
  ")": { row: 4, bit: 1 },
  _: { row: 4, bit: 0 },
  "<": { row: 2, bit: 3 },
  ">": { row: 2, bit: 4 },
  ";": { row: 5, bit: 1 },
  '"': { row: 5, bit: 0 },
  "^": { row: 6, bit: 4 },
  "-": { row: 6, bit: 3 },
  "+": { row: 6, bit: 2 },
  "=": { row: 6, bit: 1 },
  ".": { row: 7, bit: 2 },
  ",": { row: 7, bit: 3 },
  "*": { row: 7, bit: 4 },
  "?": { row: 0, bit: 3 },
  "/": { row: 0, bit: 4 },
  "£": { row: 0, bit: 2 },
  ":": { row: 0, bit: 1 },
};
